# Generated by Django 5.2 on 2025-04-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityuser',
            name='is_seller',
            field=models.BooleanField(default=True),
        ),
    ]
