# Generated by Django 5.2 on 2025-04-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_communityuser_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='communityposting',
            name='offerings',
            field=models.ManyToManyField(blank=True, help_text='Any add-ons or extras for this listing', related_name='postings', to='api.offering'),
        ),
        migrations.AddField(
            model_name='communityposting',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, help_text='Which payment options you accept', related_name='postings', to='api.paymentmethod'),
        ),
    ]
