# Generated by Django 5.2 on 2025-04-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_communityuser_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
