# Generated by Django 5.2 on 2025-04-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_offering_paymentmethod_communityposting_offerings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityposting',
            name='offerings',
            field=models.ManyToManyField(blank=True, help_text='Any add‑ons or extras for this listing', related_name='postings', to='api.offering'),
        ),
    ]
