# Generated by Django 5.2 on 2025-04-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_communityuser_profile_picture'),
        ('api', '0004_tag_message_listingtag'),
    ]

    operations = [
    ]
