# Generated by Django 5.2 on 2025-04-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_details',
            field=models.JSONField(blank=True, help_text='Buyer name, email, phone, and mailing address', null=True),
        ),
    ]
